### ISSUE TITLE
Hook not called when ticket created by mail_handler

### ISSUE THREAD

**Issue by jegade** [suer/redmine_webhook#13]
We use the mail handler (http://www.redmine.org/projects/redmine/wiki/RedmineReceivingEmails) to update and create tickets. But tickets created or updated by mail are not trigger the webhook.

**Comment by jegade** [comment]
@suer could we sponsor the feature to trigger for incoming mail updates? How much work it will be?

**Comment by jegade** [comment]
Pull request for Redmine itself fixed the problem https://github.com/redmine/redmine/pull/94

**Comment by jacquesbh** [comment]
@jegade Actually it didn't, since the PR hasn't been merged :( .
