### ISSUE TITLE
No rakefile found

### ISSUE THREAD

**Issue by nghoanghiep** [suer/redmine_webhook#21]
Please check, when i run, there's error:
/bitnami/redmine/plugins# rake redmine:plugins:migrate RAILS_ENV=production
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)

(See full trace by running task with --trace)

**Comment by suer** [comment]
I think that the command run successfully at `/bitnami/redmine`.
