### ISSUE TITLE
Add a Webhook via API

### ISSUE THREAD

**Issue by zer0uno** [suer/redmine_webhook#23]
Is there available an API to add a URL to a project?

I tried with the followings with the `X-Redmine-API-Key` header:

- http://myhost.com/projects/my_project/webhook_settings/create

- http://myhost.com/projects/my_project/webhook_settings/create.json

but I get an 422 Unprocessable Entity in the first case and a 401 Unauthorized in the second one.

**Comment by suer** [comment]
No, not supported.

If we want to do it, `WebhookSettingsController` may need `accept_api_auth` to accept actions.

like: 

```ruby
class WebhookSettingsController < ApplicationController
  accept_api_auth :create, :update, :destroy
```

**Comment by suer** [comment]
I added API access feature at 814bbba21dc71e11dde3987ed060604c9f52b519 in master branch.
master branch requires Redmine 4.0 or later.
If you try it with older version, you neet to cherry-pick this commit.
