### ISSUE TITLE
Directly inheriting from ActiveRecord::Migration is not supported.

### ISSUE THREAD

**Issue by likesubject** [suer/redmine_webhook#24]
Directly inheriting from ActiveRecord::Migration is not supported. Please specify the Rails release the migration was written for:

  class CreateWebhooks < ActiveRecord::Migration[4.2]

**Comment by Fgruntjes** [comment]
Same issue here

**Comment by defensivedepth** [comment]
Edit  https://github.com/suer/redmine_webhook/blob/master/db/migrate/001_create_webhooks.rb#L1

`class CreateWebhooks < ActiveRecord::Migration[5.0]`

**Comment by suer** [comment]
Fixed: 9acb46708aba8585cbb7a23467449a8d6e5db815

please try HEAD of master branch.
