### ISSUE TITLE
webhook can not work

### ISSUE THREAD

**Issue by xudatou-94** [suer/redmine_webhook#47]
redmine version 5.0.4.stable
download redmine_webhook code in master branch
when add new issue i get a err log in production.log

[ERROR --: uninitialized constant redmine webhook::webhook listener::faraday]

how to solve it

**Comment by yzzy** [comment]
did you run `bundle install` after cloning the repo?

**Comment by xudatou-94** [comment]
> did you run `bundle install` after cloning the repo?
I have run the command and still  get the same error

**Comment by xudatou-94** [comment]
> 

I reinstalled the plugin, work fine
