### ISSUE TITLE
randomly wrong jsondata sent by the webhook

### ISSUE THREAD

**Issue by caccwin** [suer/redmine_webhook#53]
hi,I'm using this plugin with redmine v5.0.6,and create two webhook send to different backend
that's almost work but sometime the jsondata sent by the plugin can't parse
![image](https://github.com/suer/redmine_webhook/assets/6437599/9907fa7c-48c9-40e0-b99f-9fbf8737eb0b)
it looks linke the jsondata has extra "," course this error:
![image](https://github.com/suer/redmine_webhook/assets/6437599/c2047f25-cc7b-4379-8eb1-204ff43146a7)

is this plugin has problem work with the custom field?

**Comment by yzzy** [comment]
@caccwin These errors belongs to the same issue and/or to the same custom field (maybe in different issues)?

**Comment by caccwin** [comment]
@yzzy in same issue, the position of this "," won't change when the error happen, but change to different custom field in different issue

**Comment by yzzy** [comment]
[custom_field_value_wrapper.rb.gz](https://github.com/suer/redmine_webhook/files/13511251/custom_field_value_wrapper.rb.gz)
Try to `gunzip` the attachment and replace the file `${REDMINE_ROOT}/plugins/redmine_webhook/lib/redmine_webhook/custom_field_value_wrapper.rb`, then restart Redmine and check again.

**Comment by caccwin** [comment]
@yzzy 
still get errors with "," ,but i notices this wrong "," isn't appeal in the custom field this time...
![image](https://github.com/suer/redmine_webhook/assets/6437599/e8f86c5f-070c-40a8-970a-3cc0c6fd2053)

**Comment by yzzy** [comment]
That's something really strange. These commas should not be there in any way.
I've added some debug messages to `webhook_listener.rb` in the same directory. Replace this file from attachment, restart Redmine and look at `${REDMINE_ROOT}/log/production.log` for `!!! Webhook:` and `!!! Payload:` lines. Please check if there are commas in payload.
[webhook_listener.rb.gz](https://github.com/suer/redmine_webhook/files/13520784/webhook_listener.rb.gz)

**Comment by caccwin** [comment]
@yzzy 
very thanks for help,
the redmine log shows the data sent has no wrong commas,it looks my nodejs program to receive the data has some problems...

**Comment by yzzy** [comment]
@caccwin don't forget to restore patched files and close this issue
